version: '3.7'
services:
   haproxy:
      image: haproxy:1.7
      volumes:
         - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
         - ${DATA_DIR:-./data}/letsencrypt:/etc/letsencrypt
      networks:
         - webrtc-learning
         - haproxy-controller_haproxy-controller

   redis:
      image: redis:latest
      networks:
         - webrtc-learning

   server:
      image: benbergstein/webrtc-learning:latest
      ports:
         - 3001:3001
      command: ["server"]
      volumes:
         - .:/app
      networks:
         - webrtc-learning
      depends_on:
         - redis

   client:
      image: benbergstein/webrtc-learning:latest
      ports:
         - 3000:3000
      volumes:
         - .:/app
      networks:
         - webrtc-learning
      environment:
         - REACT_APP_HOST=http://dev-1.wips.link:3001

networks:
   webrtc-learning:
   haproxy-controller_haproxy-controller:
      external: true
