version: '3.7'
services:
   haproxy:
      image: haproxy:1.7
      volumes:
         - ./config/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
         - ${DATA_DIR:-./data}/letsencrypt:/etc/letsencrypt
      networks:
         - webrtc-learning
         - haproxy-controller_haproxy-controller

   routeservice:
      image: benbergstein/webrtc-learning:latest
      ports:
         - 3000:3000
      volumes:
         - .:/app
      networks:
         - webrtc-learning

networks:
   webrtc-learning:
   haproxy-controller_haproxy-controller:
      external: true
