version: '3.7'

services:
  app:
    image: 'benbergstein/webrtc-learning:latest'
    command: ["server:prod"]
    volumes:
       - ./:/app
    networks:
       - haproxy-controller_haproxy-controller
    environment:
      - REACT_APP_HOST

networks:
   haproxy-controller_haproxy-controller:
      external: true
