version: '3.7'

services:
  app:
    image: 'benbergstein/webrtc-learning:latest'
    command: ["server:prod"]
    volumes:
       - ./:/app
    networks:
       - haproxy-controller_haproxy-controller
    environment:
      - REACT_APP_HOST
    depends_on:
       - redis

  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data/redis:/data
    networks:
       - haproxy-controller_haproxy-controller


networks:
   haproxy-controller_haproxy-controller:
      external: true
